[package]
name = "webp"
version = "0.0.0"
authors = ["Jared Forth <jaredforthdev@gmail.com>"]
edition = "2018"

description = "WebP conversion library | comming soon"
license = "GPL-3.0-or-later"

homepage = "https://github.com/jaredforth/webp"
repository = "https://github.com/jaredforth/webp.git"

[dependencies]
libwebp-sys = "0.2.0"
image = { version = "0.22.3", optional = true }

[features]
default = ["image-conversion"]
image-conversion = [ "image" ]

# disable optimizations for running memory leak analysis
# cargo watch -w src -s "env RUSTFLAGS=\"-Z sanitizer=leak\" cargo +nightly test --target x86_64-unknown-linux-gnu"
[profile.dev]
opt-level = 1

[dev-dependencies]
image = "0.22.3"